### PR TITLE
UI/UX Improvement

### PR DESCRIPTION
**Pull request by jssol**
- Improve the general look and feel of the application
- [Live Demo](https://jssol.github.io/api-based-webapp/)

### CODE REVIEW

**Comment by jssol** [comment]
I am sorting the items by their type and counting them into different counters.

**Review by Ismailco — CHANGES_REQUESTED** [review]
Good 👍🏼
###  ⚠️ You can work on the individual movie comment page to be responsive!
I liked how you handled the types in the header, are they just to count the items in each type? if that's the case, Nice job 🥳

**Comment by jssol** [comment]
> Good 👍🏼
> 
> ###  You can work on the individual movie comment page to be responsive!
> I liked how you handled the types in the header, are they just to count the items in each type? if that's the case, Nice job partying_face

Let me do that and I am going to get back very soon

**Comment by jssol** [comment]
@Ismailco I am going to merge this PR and I will work on the global responsiveness of the website because the header is breaking the popup.

**Pull request merged**
