### PR TITLE
Add new likes

### LINKED ISSUE #9: [3pt]  - Create feature: add  new like - Student A
When the user clicks on the Like button of an item (on Homepage), the interaction is recorded in the Involvement API and the screen is updated.

### PR DESCRIPTION
**Pull request by Ismailco**
- Send new Likes to the API.
- Change the color of the ❤️ to red after clicking.

### CODE REVIEW

**Review by jssol — CHANGES_REQUESTED** [review]
### Well done implementing this feature :tada:
However, I think we can improve in some areas:
- The time it takes to display the likes is too long, we can look for a way to shorten it.
- We can increment the likes count directly when the user clicks, instead of waiting for the data from the API.
- It can be a great UX improvement if the liked item is displayed as such even after page reload.

**Comment by jssol** [comment]
Kindly check the new design proposal and give me your thoughts about it.
- [Live Demo](https://jssol.github.io/api-based-webapp/)

**Comment by Ismailco** [comment]
we can do that in another PR this one is just for adding likes.
> We can increment the likes count directly when the user clicks, instead of waiting for the data from the API.

ok I will work on that

**Comment by Ismailco** [comment]
> The time it takes to display the likes is too long, we can look for a way to shorten it.

I changed the code, now it's good
> We can increment the likes count directly when the user clicks, instead of waiting for the data from the API.

Ok I fixed this issue
> It can be a great UX improvement if the liked item is displayed as such even after page reload.

Ok I fixed this issue

**Review by jssol — APPROVED** [review]
Nice job implementing the changes, we can merge this one and move to the next milestone :100:

**Pull request merged**
